DEFAULT_SITE_CONTENT = {
    'siteTitle': 'مهدی پیرحیاتی | توسعه‌دهنده بک‌اند Python و Django',
    'faviconUrl': '/favicon.svg',
    'logoUrl': '',
    'fullName': 'مهدی پیرحیاتی',
    'initials': 'MP',
    'role': 'توسعه‌دهنده بک‌اند Python و Django',
    'heroSubtitle': 'ساخت APIهای تمیز، بک‌اندهای قابل توسعه و تجربه‌های Full Stack کاربردی.',
    'heroDescription': 'من دانشجوی مهندسی نرم‌افزار و علاقه‌مند به توسعه وب هستم. تمرکز اصلی من روی Python، Django، Django REST Framework و PostgreSQL است و با ساخت پروژه‌های واقعی برای ورود حرفه‌ای به بازار کار آماده می‌شوم.',
    'aboutTitle': 'مسیرم را با یادگیری عمیق بک‌اند و ساخت پروژه واقعی جلو می‌برم.',
    'aboutDescription': 'تمرکز من روی نوشتن کد تمیز، طراحی API قابل فهم و کار با داده‌هاست؛ چیزهایی که در پروژه‌های واقعی ارزش خودشان را نشان می‌دهند.',
    'aboutPrimary': 'من مهدی پیرحیاتی، دانشجوی مهندسی نرم‌افزار و علاقه‌مند به توسعه وب هستم. تمرکز اصلی من روی توسعه بک‌اند با Python و Django، طراحی API و کار با پایگاه‌داده PostgreSQL است.',
    'aboutSecondary': 'با ساخت پروژه‌های واقعی، مهارت‌هایم را مرحله‌به‌مرحله گسترش می‌دهم و تلاش می‌کنم برای ورود حرفه‌ای به بازار کار آماده شوم. برای من کیفیت ساختار، خوانایی کد و قابلیت توسعه اهمیت زیادی دارد.',
    'location': 'ملایر، ایران',
    'education': 'کارشناسی مهندسی نرم‌افزار',
    'focus': 'علاقه‌مند به توسعه بک‌اند',
    'availability': 'آماده همکاری و کارآموزی',
    'email': 'mahdipirhayati1382@gmail.com',
    'phone': '09014105191',
    'githubUrl': 'https://github.com/mahdipir82',
    'githubLabel': 'github.com/mahdipir82',
    'linkedinUrl': 'https://www.linkedin.com/in/mahdi-pirhayati/',
    'linkedinLabel': 'mahdi-pirhayati',
    'contactTitle': 'برای همکاری، کارآموزی یا گفت‌وگو درباره پروژه در دسترسم.',
    'contactDescription': 'فرم زیر پیام را از طریق برنامه ایمیل شما آماده می‌کند و هیچ کلید یا سرویس محرمانه‌ای در کد استفاده نشده است.',
    'backgroundColor': '#020817',
    'backgroundColorEnd': '#020617',
    'accentColor': '#67e8f9',
    'accentSoftColor': '#22d3ee',
    'secondaryAccentColor': '#8b5cf6',
    'cardTintColor': '#0f172a',
    'animationEnabled': True,
    'animationSpeed': 1,
    'animationIntensity': 1,
}
