DEFAULT_PROJECTS = [
    {
        'title': 'Code82-Commerce',
        'persian_title': 'فروشگاه اینترنتی Code82',
        'short_description': 'فروشگاه اینترنتی Full Stack با بک‌اند Django و Django REST Framework و فرانت‌اند React.',
        'full_description': 'یک فروشگاه اینترنتی Full Stack با معماری مدرن که بک‌اند آن با Django و Django REST Framework و فرانت‌اند آن با React توسعه داده می‌شود. تمرکز پروژه روی احراز هویت، مدیریت محصولات، سبد خرید و پنل مدیریتی اختصاصی است.',
        'image': '',
        'image_alt': 'نمای گرافیکی Placeholder برای پروژه فروشگاه اینترنتی Code82',
        'technologies': ['Python', 'Django', 'Django REST Framework', 'PostgreSQL', 'React', 'Tailwind CSS'],
        'features': [
            'احراز هویت کاربران',
            'ثبت‌نام با شماره تلفن و OTP',
            'مدیریت محصولات و دسته‌بندی‌ها',
            'سبد خرید',
            'پنل مدیریتی اختصاصی',
            'مدیریت قالب سایت',
            'طراحی واکنش‌گرا',
        ],
        'github_url': '',
        'live_url': '',
        'status': 'در حال توسعه',
        'featured': True,
        'sort_order': 0,
    },
]
